name: Deploy/Staging/Backend

env:
  BUILD_ARTIFACT: staging-backend-build

on:
  push:
    branches: ["dev"]
    paths: ["apps/backend/**"]

jobs:
  prettier:
    name: Check Format
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "yarn"

      - name: Install deps
        run: yarn install --frozen-lockfile

      - name: Run Prettier
        working-directory: ./apps/backend
        run: yarn check-format

  build:
    name: Build
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "yarn"

      - name: Install deps
        run: yarn install --frozen-lockfile

      - name: Create multi-select-field plugin build
        working-directory: ./apps/backend/src/plugins/multi-select-field
        run: NODE_ENV=production yarn build

      - name: Create soft-delete plugin build
        working-directory: ./apps/backend/src/plugins/soft-delete
        run: NODE_ENV=production yarn build

      - name: Create input-real-time-validation plugin build
        working-directory: ./apps/backend/src/plugins/input-real-time-validation
        run: NODE_ENV=production yarn build

      - name: Create unique-domains plugin build
        working-directory: ./apps/backend/src/plugins/unique-domains
        run: NODE_ENV=production yarn build

      - name: Create build
        working-directory: ./apps/backend
        run: NODE_ENV=production yarn build

      - name: Generate dist
        working-directory: ./apps/backend
        # remove .ebextensions as it contains configuration for load balancer
        # which does not exist in staging environment
        run: zip -r deploy.zip * .[^.]* -x "**node_modules**" -x "*.ebextensions*"

      - name: Upload dist
        uses: actions/upload-artifact@v3
        with:
          name: $BUILD_ARTIFACT
          retention-days: 1
          path: ./apps/backend/deploy.zip

  deploy:
    needs: [prettier, build]
    name: Deploy to AWS
    runs-on: ubuntu-latest

    steps:
      - name: Download dist
        uses: actions/download-artifact@v3
        with:
          name: $BUILD_ARTIFACT

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          use_existing_version_if_available: true
          application_name: landing-page-cms-backend
          environment_name: landing-page-cms-backend-staging-v18
          version_label: ${{github.SHA}}
          region: eu-central-1
          deployment_package: deploy.zip
