name: Deploy/Staging/Frontend

env:
  BUILD_ARTIFACT: staging-frontend-build
  DIRECTORY: ./apps/frontend

on:
  push:
    branches: ["dev"]
    # paths: ["apps/frontend/**"]

jobs:
  prettier:
    name: Check Format
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Cache turbo
        uses: actions/cache@v3
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: "yarn"

      - name: Install deps
        run: yarn install --frozen-lockfile

      - name: Run Prettier
        working-directory: $DIRECTORY
        run: yarn check-format

  build-and-test:
    name: Build & Test
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Cache turbo
        uses: actions/cache@v3
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: "yarn"

      - name: Install deps
        run: yarn install --frozen-lockfile

      - name: Create build
        working-directory: $DIRECTORY
        run: yarn build
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          NEXT_PUBLIC_SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          NEXT_PUBLIC_API_ROUTE: "RCooqUQMNl77xg89tP848X6rETMeCapGNIUyzuz6oZzhOd7SHfPcUi6kYeIcZ52f"

      - name: Test (Unit)
        working-directory: $DIRECTORY
        run: yarn test

      - name: Test (E2E)
        working-directory: $DIRECTORY
        run: yarn test:e2e:run

      - name: Generate dist
        working-directory: $DIRECTORY
        run: zip -r deploy.zip * .[^.]* -x "**node_modules**" -x "*.ebextensions*"

      - name: Upload dist
        uses: actions/upload-artifact@v3
        with:
          name: $BUILD_ARTIFACT
          retention-days: 5
          path: ./apps/frontend/deploy.zip

  deploy:
    needs: [prettier, build-and-test]
    name: Deploy to AWS
    runs-on: ubuntu-latest

    steps:
      - name: Download dist
        uses: actions/download-artifact@v3
        with:
          name: $BUILD_ARTIFACT

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          use_existing_version_if_available: true
          application_name: landing-page-cms-frontend
          environment_name: landing-page-cms-frontend-staging
          version_label: ${{github.SHA}}
          region: eu-central-1
          deployment_package: deploy.zip
