name: Deploy/Staging/Frontend

env:
  BUILD_ARTIFACT: staging-frontend-build

on:
  push:
    branches: ["dev"]
    # paths: ["apps/frontend/**"]

jobs:
  build:
    name: Build and Test
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: "yarn"

      - name: Install
        run: yarn

      - name: Check Format
        working-directory: ./apps/frontend
        run: yarn check-format

      - name: Build
        working-directory: ./apps/frontend
        run: yarn build
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          NEXT_PUBLIC_SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          NEXT_PUBLIC_API_ROUTE: "RCooqUQMNl77xg89tP848X6rETMeCapGNIUyzuz6oZzhOd7SHfPcUi6kYeIcZ52f"

      - name: Generate deployment package
        working-directory: ./apps/frontend
        run: zip -r deploy.zip * -x "**node_modules**"

      - name: Upload build
        uses: actions/upload-artifact@v3
        with:
          name: $BUILD_ARTIFACT
          retention-days: 5
          path: ./apps/frontend/deploy.zip

      - name: Test (Unit)
        working-directory: ./apps/frontend
        run: yarn test

      - name: Test (E2E)
        working-directory: ./apps/frontend
        run: yarn test:e2e:run

  deploy:
    needs: build
    name: Deploy to AWS
    runs-on: ubuntu-latest

    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v3
        with:
          name: $BUILD_ARTIFACT
      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v13
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          use_existing_version_if_available: true
          application_name: landing-page-cms-frontend
          environment_name: landing-page-cms-frontend-staging
          version_label: ${{github.SHA}}
          region: eu-central-1
          deployment_package: deploy.zip
